# Generated by Django 4.2.9 on 2024-09-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_cartorder_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default='default/vendor1.png', null=True, upload_to='products'),
        ),
    ]
